server:
  port: 8081
  #undertow:
    #worker-threads: 1000

eureka:
  instance:
    prefer-ip-address: true
    #ip-address: 
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true

spring:
  redis:
    ssl: true
    port: 6380
    database: 15
    host: inhandao-dev.redis.cache.windows.net
    password: sqrbxAzvYVskI5lWvhiaFqMG260Pi8atNr2OCaL6yfE=

hystrix:
  # ribbon.ConnectTimeout + ribbon.ReadTimeout
  command.default.execution.isolation.thread.timeoutInMilliseconds: 43000
  command.storage-service.execution.isolation.thread.timeoutInMilliseconds: 20000

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 40000

storage:
  listOfServers: http://192.168.100.26:9000
  listOfBuckets: vietpost

zuul:
  semaphore:
    maxSemaphores: 30000
  host:
    connect-timeout-millis: 3000
    connection-request-timeout-millis: 60000

security:
  oauth2:
    resource:
      jwt:
        key-value: ENC(S1OY8tEwytr7QVrHcymlcA==)
