server:
  port: 8081

spring:
  application:
    name: api-gateway

  main:
    web-application-type: servlet
  
  servlet:  
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  redis:
    redisson:
      config: classpath:/redisson.yml
  
hystrix:
  # ribbon.ConnectTimeout + ribbon.ReadTimeout
  command.default.execution.isolation.thread.timeoutInMilliseconds: 43000
  command.storage-service.execution.isolation.thread.timeoutInMilliseconds: 20000

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 40000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0

storage-service.ribbon.NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
storage-service.ribbon.NFLoadBalancerPingClassName: com.mb.lab.banks.apigateway.utils.MinIOPingUrl
storage-service.ribbon.listOfServers: ${storage.listOfServers}
storage-service.ribbon.ConnectTimeout: 5000
storage-service.ribbon.ReadTimeout: 5000

zuul:
  add-proxy-headers: true
  add-host-header: true
  host:
    max-total-connections: 1000
    max-per-route-connections: 100
    socket-timeout-millis: 40000
    connect-timeout-millis: 3000
    connection-request-timeout-millis: 40000
  sensitiveHeaders: 
  routes:
    auth:
      path: /auth/**
      service-id: auth-server
      strip-prefix: false
    files:
      path: /files/**
      service-id: storage-service
      strip-prefix: true
    sub-admin:
      path: /api/admin/sub-admin/**
      service-id: user-service
      strip-prefix: false
    cms:
      path: /**
      service-id: cms
      strip-prefix: false

jasypt:
  encryptor:
    password: ${CONFIG_ENCRYPTOR_SECRET:n4vekQdqiGeuk_VTT_QLDT_2020}
