server:
  port: 8201
  forward-headers-strategy: native
  servlet:
    context-path: /auth

common:
  available-locales: vi,en
  default-locale: vi

spring:
  application:
    name: auth-server
    
  session:
    store-type: redis
    redis:
      namespace: "{spring:auth:sessions}"
  
  mvc:
    throw-exception-if-no-handler-found: true
  
  resources:
    cache:
      period: 604800
    
  thymeleaf:
    mode: HTML

hystrix:
  # ribbon.ConnectTimeout + ribbon.ReadTimeout
  command.default.execution.isolation.thread.timeoutInMilliseconds: 13000

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0

jasypt:
  encryptor:
    password: ${CONFIG_ENCRYPTOR_SECRET:n4vekQdqiGeuk_VTT_QLDT_2020}