server:
  port: 8201

eureka:
  instance:
    prefer-ip-address: true
    #ip-address: 
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true

common:
  web-url: http://localhost:4200

spring:
  redis:
    ssl: true
    port: 6380
    database: 15
    host: inhandao-dev.redis.cache.windows.net
    password: sqrbxAzvYVskI5lWvhiaFqMG260Pi8atNr2OCaL6yfE=
  
security:
  oauth2:
    authorization:
      jwt:
        key-value: ENC(S1OY8tEwytr7QVrHcymlcA==)
      client-details:
        web-cms:
          client-id: app
          client-secret: 123456
          grant-type: authorization_code,refresh_token
          scope: read,write
          refresh-token-validity: 1800
          access-token-validity: 1200
          redirect-uri: http://localhost:4200/login

          